### ISSUE TITLE
MessageQueue: Handler (android.os.Handler) {cdcc738} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by ve3344** [jaredrummler/AndroidShell#13]
```
11-28 07:00:33.699 W/art: Long monitor contention event with owner method=int libcore.io.Posix.readBytes(java.io.FileDescriptor, java.lang.Object, int, int) from Posix.java:4294967294 waiters=0 for 14.898s
11-28 07:00:33.705 W/art: Long monitor contention event with owner method=void java.io.FileInputStream.close() from FileInputStream.java:114 waiters=0 for 14.904s
11-28 07:00:33.705 W/art: Long monitor contention event with owner method=void java.io.FileInputStream.close() from FileInputStream.java:114 waiters=1 for 14.838s
11-28 07:00:33.706 W/art: Long monitor contention event with owner method=void java.lang.Object.wait!() from Object.java:4294967294 waiters=0 for 31.268s
11-28 07:00:33.723 W/MessageQueue: Handler (android.os.Handler) {cdcc738} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {cdcc738} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.jaredrummler.android.shell.Shell$Interactive.postCallback(Shell.java:1383)
        at com.jaredrummler.android.shell.Shell$Interactive.runNextCommand(Shell.java:1289)
        at com.jaredrummler.android.shell.Shell$Interactive.runNextCommand(Shell.java:1178)
        at com.jaredrummler.android.shell.Shell$Interactive.addCommand(Shell.java:1151)
        at com.jaredrummler.android.shell.Shell$Console.run(Shell.java:1761)
        at com.jaredrummler.android.shell.Shell$SU.run(Shell.java:374)
```

**Comment by jaredrummler** [comment]
Please try the new updated library (see README for more info).
